domain_path: E:\VLSI_project\vitis_workspace\platform_1\export\platform_1\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\VITIS\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
